[2025-05-03T12:28:45.273+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-03T12:28:45.318+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-03T12:27:26.480506+00:00 [queued]>
[2025-05-03T12:28:45.339+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-03T12:27:26.480506+00:00 [queued]>
[2025-05-03T12:28:45.358+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-03T12:28:45.383+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): model_data> on 2025-05-03 12:27:26.480506+00:00
[2025-05-03T12:28:45.403+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2219) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-03T12:28:45.409+0000] {standard_task_runner.py:72} INFO - Started process 2234 to run task
[2025-05-03T12:28:45.408+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'model_data', 'manual__2025-05-03T12:27:26.480506+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmp53uzq6t1']
[2025-05-03T12:28:45.410+0000] {standard_task_runner.py:105} INFO - Job 253: Subtask model_data
[2025-05-03T12:28:45.518+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.model_data manual__2025-05-03T12:27:26.480506+00:00 [running]> on host 8280c28b7f0f
[2025-05-03T12:28:45.675+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='model_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T12:27:26.480506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T12:27:26.480506+00:00'
[2025-05-03T12:28:45.679+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-03T12:28:45.680+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-03T12:28:45.681+0000] {logging_mixin.py:190} INFO - Current task name:model_data state:running start_date:2025-05-03 12:28:45.319726+00:00
[2025-05-03T12:28:45.682+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-03T12:28:45.683+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-03T12:28:45.699+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-03T12:28:45.783+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-03T12:28:45.805+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-03T12:28:45.807+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=model_data, run_id=manual__2025-05-03T12:27:26.480506+00:00, execution_date=20250503T122726, start_date=20250503T122845, end_date=20250503T122845
[2025-05-03T12:28:45.868+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-03T12:28:45.869+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-03T12:28:45.871+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-03 12:27:26.506108+00:00
[2025-05-03T12:28:45.871+0000] {logging_mixin.py:190} INFO - Task hostname:8280c28b7f0f operator:PythonOperator
[2025-05-03T12:28:45.910+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-03T12:28:45.960+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T12:28:45.965+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
