[2025-05-06T23:05:13.707+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-06T23:05:13.749+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.export_to_csv manual__2025-05-06T20:00:25.137792+00:00 [queued]>
[2025-05-06T23:05:13.770+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.export_to_csv manual__2025-05-06T20:00:25.137792+00:00 [queued]>
[2025-05-06T23:05:13.771+0000] {taskinstance.py:2867} INFO - Starting attempt 6 of 7
[2025-05-06T23:05:13.797+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): export_to_csv> on 2025-05-06 20:00:25.137792+00:00
[2025-05-06T23:05:13.821+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=9512) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-06T23:05:13.826+0000] {standard_task_runner.py:72} INFO - Started process 9527 to run task
[2025-05-06T23:05:13.827+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'export_to_csv', 'manual__2025-05-06T20:00:25.137792+00:00', '--job-id', '665', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpu7nsj9eh']
[2025-05-06T23:05:13.829+0000] {standard_task_runner.py:105} INFO - Job 665: Subtask export_to_csv
[2025-05-06T23:05:13.921+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.export_to_csv manual__2025-05-06T20:00:25.137792+00:00 [running]> on host 8280c28b7f0f
[2025-05-06T23:05:14.095+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='export_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T20:00:25.137792+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T20:00:25.137792+00:00'
[2025-05-06T23:05:14.099+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-06T23:05:14.100+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-06T23:05:14.101+0000] {logging_mixin.py:190} INFO - Current task name:export_to_csv state:running start_date:2025-05-06 23:05:13.750947+00:00
[2025-05-06T23:05:14.101+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-06T23:05:14.102+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-06T23:05:14.119+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-06T23:05:14.159+0000] {warnings.py:112} WARNING - /opt/***/dags/storeData.py:96: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-05-06T23:05:14.278+0000] {logging_mixin.py:190} INFO - ✅ Données exportées avec succès vers reviews_export.csv
[2025-05-06T23:05:14.280+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-06T23:05:14.303+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-06T23:05:14.305+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=export_to_csv, run_id=manual__2025-05-06T20:00:25.137792+00:00, execution_date=20250506T200025, start_date=20250506T230513, end_date=20250506T230514
[2025-05-06T23:05:14.349+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-06T23:05:14.351+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-06T23:05:14.352+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-06 23:00:53.773813+00:00
[2025-05-06T23:05:14.353+0000] {logging_mixin.py:190} INFO - Task hostname:8280c28b7f0f operator:PythonOperator
[2025-05-06T23:05:14.410+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-06T23:05:14.454+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T23:05:14.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
