[2025-05-08T18:51:21.043+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T18:51:21.078+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.analyze_sentiment scheduled__2025-05-07T00:00:00+00:00 [queued]>
[2025-05-08T18:51:21.097+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.analyze_sentiment scheduled__2025-05-07T00:00:00+00:00 [queued]>
[2025-05-08T18:51:21.098+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-08T18:51:21.124+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): analyze_sentiment> on 2025-05-07 00:00:00+00:00
[2025-05-08T18:51:21.148+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=194) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-08T18:51:21.158+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'analyze_sentiment', 'scheduled__2025-05-07T00:00:00+00:00', '--job-id', '796', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpj6asq9cc']
[2025-05-08T18:51:21.160+0000] {standard_task_runner.py:105} INFO - Job 796: Subtask analyze_sentiment
[2025-05-08T18:51:21.160+0000] {standard_task_runner.py:72} INFO - Started process 209 to run task
[2025-05-08T18:51:21.355+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.analyze_sentiment scheduled__2025-05-07T00:00:00+00:00 [running]> on host 9ce8fafe7ab9
[2025-05-08T18:51:21.581+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='tonemail@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='analyze_sentiment' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-07T00:00:00+00:00'
[2025-05-08T18:51:21.584+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-08T18:51:21.585+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-08T18:51:21.586+0000] {logging_mixin.py:190} INFO - Current task name:analyze_sentiment state:running start_date:2025-05-08 18:51:21.079824+00:00
[2025-05-08T18:51:21.587+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-08T18:51:21.588+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-08T18:51:21.608+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-08T18:51:23.046+0000] {warnings.py:112} WARNING - /opt/***/dags/storeData.py:319: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-05-08T18:51:23.347+0000] {logging_mixin.py:190} INFO - Sentiment analysis completed.
[2025-05-08T18:51:23.359+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-08T18:51:23.381+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-08T18:51:23.383+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=analyze_sentiment, run_id=scheduled__2025-05-07T00:00:00+00:00, execution_date=20250507T000000, start_date=20250508T185121, end_date=20250508T185123
[2025-05-08T18:51:23.446+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-08T18:51:23.448+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-08T18:51:23.449+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-08 18:48:15.030563+00:00
[2025-05-08T18:51:23.450+0000] {logging_mixin.py:190} INFO - Task hostname:9ce8fafe7ab9 operator:PythonOperator
[2025-05-08T18:51:23.477+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-08T18:51:23.562+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-08T18:51:23.566+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
