[2025-05-05T21:52:50.710+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-05T21:52:50.750+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.remove_duplicates scheduled__2025-05-04T00:00:00+00:00 [queued]>
[2025-05-05T21:52:50.770+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.remove_duplicates scheduled__2025-05-04T00:00:00+00:00 [queued]>
[2025-05-05T21:52:50.789+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 5
[2025-05-05T21:52:50.825+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): remove_duplicates> on 2025-05-04 00:00:00+00:00
[2025-05-05T21:52:50.848+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'remove_duplicates', 'scheduled__2025-05-04T00:00:00+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpmq6fzsno']
[2025-05-05T21:52:50.846+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-05T21:52:50.851+0000] {standard_task_runner.py:105} INFO - Job 522: Subtask remove_duplicates
[2025-05-05T21:52:50.852+0000] {standard_task_runner.py:72} INFO - Started process 1682 to run task
[2025-05-05T21:52:50.938+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.remove_duplicates scheduled__2025-05-04T00:00:00+00:00 [running]> on host 8280c28b7f0f
[2025-05-05T21:52:51.161+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='remove_duplicates' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-04T00:00:00+00:00'
[2025-05-05T21:52:51.166+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-05T21:52:51.167+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-05T21:52:51.168+0000] {logging_mixin.py:190} INFO - Current task name:remove_duplicates state:running start_date:2025-05-05 21:52:50.751942+00:00
[2025-05-05T21:52:51.169+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-05T21:52:51.169+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-05T21:52:51.187+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-05T21:52:51.213+0000] {logging_mixin.py:190} INFO - Duplicate reviews removed.
[2025-05-05T21:52:51.216+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-05T21:52:51.243+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-05T21:52:51.245+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=remove_duplicates, run_id=scheduled__2025-05-04T00:00:00+00:00, execution_date=20250504T000000, start_date=20250505T215250, end_date=20250505T215251
[2025-05-05T21:52:51.291+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-05T21:52:51.292+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-05T21:52:51.293+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-05 21:52:23.310129+00:00
[2025-05-05T21:52:51.294+0000] {logging_mixin.py:190} INFO - Task hostname:8280c28b7f0f operator:PythonOperator
[2025-05-05T21:52:51.313+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-05T21:52:51.364+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-05T21:52:51.368+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
