[2025-05-03T16:06:09.846+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-03T16:06:09.896+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.generate_dbt_docs manual__2025-05-03T15:59:08.005169+00:00 [queued]>
[2025-05-03T16:06:09.918+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.generate_dbt_docs manual__2025-05-03T15:59:08.005169+00:00 [queued]>
[2025-05-03T16:06:09.937+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-03T16:06:09.963+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): generate_dbt_docs> on 2025-05-03 15:59:08.005169+00:00
[2025-05-03T16:06:09.986+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6640) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-03T16:06:09.990+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'generate_dbt_docs', 'manual__2025-05-03T15:59:08.005169+00:00', '--job-id', '368', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmps90a3v2i']
[2025-05-03T16:06:09.993+0000] {standard_task_runner.py:72} INFO - Started process 6655 to run task
[2025-05-03T16:06:09.993+0000] {standard_task_runner.py:105} INFO - Job 368: Subtask generate_dbt_docs
[2025-05-03T16:06:10.100+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.generate_dbt_docs manual__2025-05-03T15:59:08.005169+00:00 [running]> on host 8280c28b7f0f
[2025-05-03T16:06:10.311+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='generate_dbt_docs' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T15:59:08.005169+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T15:59:08.005169+00:00'
[2025-05-03T16:06:10.314+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-03T16:06:10.316+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-03T16:06:10.317+0000] {logging_mixin.py:190} INFO - Current task name:generate_dbt_docs state:running start_date:2025-05-03 16:06:09.898109+00:00
[2025-05-03T16:06:10.318+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-03T16:06:10.319+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-03T16:06:10.322+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-03T16:06:10.328+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_project/bank_reviews_dbt && dbt docs generate']
[2025-05-03T16:06:10.364+0000] {subprocess.py:99} INFO - Output:
[2025-05-03T16:06:15.036+0000] {subprocess.py:106} INFO - [0m16:06:15  Running with dbt=1.9.4
[2025-05-03T16:06:15.710+0000] {subprocess.py:106} INFO - [0m16:06:15  Registered adapter: postgres=1.9.0
[2025-05-03T16:06:16.698+0000] {subprocess.py:106} INFO - [0m16:06:16  Found 5 models, 12 data tests, 433 macros
[2025-05-03T16:06:16.707+0000] {subprocess.py:106} INFO - [0m16:06:16
[2025-05-03T16:06:16.709+0000] {subprocess.py:106} INFO - [0m16:06:16  Concurrency: 1 threads (target='dev')
[2025-05-03T16:06:16.710+0000] {subprocess.py:106} INFO - [0m16:06:16
[2025-05-03T16:06:17.894+0000] {subprocess.py:106} INFO - [0m16:06:17  Building catalog
[2025-05-03T16:06:18.130+0000] {subprocess.py:106} INFO - [0m16:06:18  Catalog written to /opt/***/dbt_project/bank_reviews_dbt/target/catalog.json
[2025-05-03T16:06:22.982+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-03T16:06:23.031+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-03T16:06:23.033+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=generate_dbt_docs, run_id=manual__2025-05-03T15:59:08.005169+00:00, execution_date=20250503T155908, start_date=20250503T160609, end_date=20250503T160623
[2025-05-03T16:06:23.078+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-03T16:06:23.079+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-03T16:06:23.080+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-03 15:59:08.081088+00:00
[2025-05-03T16:06:23.081+0000] {logging_mixin.py:190} INFO - Task hostname:8280c28b7f0f operator:BashOperator
[2025-05-03T16:06:23.104+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-03T16:06:23.149+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T16:06:23.153+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
