[2025-05-07T01:16:40.617+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-07T01:16:40.659+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.detect_language manual__2025-05-07T01:02:20.058495+00:00 [queued]>
[2025-05-07T01:16:40.681+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.detect_language manual__2025-05-07T01:02:20.058495+00:00 [queued]>
[2025-05-07T01:16:40.685+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-07T01:16:40.716+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): detect_language> on 2025-05-07 01:02:20.058495+00:00
[2025-05-07T01:16:40.738+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=12187) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-07T01:16:40.743+0000] {standard_task_runner.py:72} INFO - Started process 12202 to run task
[2025-05-07T01:16:40.743+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'detect_language', 'manual__2025-05-07T01:02:20.058495+00:00', '--job-id', '726', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmp4yg2wxoy']
[2025-05-07T01:16:40.745+0000] {standard_task_runner.py:105} INFO - Job 726: Subtask detect_language
[2025-05-07T01:16:40.829+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.detect_language manual__2025-05-07T01:02:20.058495+00:00 [running]> on host 8280c28b7f0f
[2025-05-07T01:16:40.976+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='detect_language' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T01:02:20.058495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T01:02:20.058495+00:00'
[2025-05-07T01:16:40.980+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-07T01:16:40.981+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-07T01:16:40.982+0000] {logging_mixin.py:190} INFO - Current task name:detect_language state:running start_date:2025-05-07 01:16:40.661697+00:00
[2025-05-07T01:16:40.984+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-07T01:16:40.985+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-07T01:16:41.003+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-07T01:17:02.829+0000] {warnings.py:112} WARNING - /opt/***/dags/storeData.py:358: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-05-07T01:17:02.917+0000] {logging_mixin.py:190} INFO - Language detection completed.
[2025-05-07T01:17:02.921+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-07T01:17:02.949+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-07T01:17:02.950+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=detect_language, run_id=manual__2025-05-07T01:02:20.058495+00:00, execution_date=20250507T010220, start_date=20250507T011640, end_date=20250507T011702
[2025-05-07T01:17:02.998+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-07T01:17:02.999+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-07T01:17:03.000+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-07 01:02:20.137662+00:00
[2025-05-07T01:17:03.000+0000] {logging_mixin.py:190} INFO - Task hostname:8280c28b7f0f operator:PythonOperator
[2025-05-07T01:17:03.065+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-07T01:17:03.128+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-07T01:17:03.132+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
