[2025-05-03T13:25:38.773+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-03T13:25:38.825+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-03T13:24:29.606740+00:00 [queued]>
[2025-05-03T13:25:38.845+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-03T13:24:29.606740+00:00 [queued]>
[2025-05-03T13:25:38.863+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-03T13:25:38.889+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): model_data> on 2025-05-03 13:24:29.606740+00:00
[2025-05-03T13:25:38.907+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3834) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-03T13:25:38.911+0000] {standard_task_runner.py:72} INFO - Started process 3849 to run task
[2025-05-03T13:25:38.911+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'model_data', 'manual__2025-05-03T13:24:29.606740+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmp9_tnuida']
[2025-05-03T13:25:38.913+0000] {standard_task_runner.py:105} INFO - Job 302: Subtask model_data
[2025-05-03T13:25:38.994+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.model_data manual__2025-05-03T13:24:29.606740+00:00 [running]> on host 8280c28b7f0f
[2025-05-03T13:25:39.194+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='model_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T13:24:29.606740+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T13:24:29.606740+00:00'
[2025-05-03T13:25:39.197+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-03T13:25:39.198+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-03T13:25:39.199+0000] {logging_mixin.py:190} INFO - Current task name:model_data state:running start_date:2025-05-03 13:25:38.826764+00:00
[2025-05-03T13:25:39.200+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-03T13:25:39.201+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-03T13:25:39.222+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-03T13:25:39.285+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-03T13:25:39.305+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-03T13:25:39.307+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=model_data, run_id=manual__2025-05-03T13:24:29.606740+00:00, execution_date=20250503T132429, start_date=20250503T132538, end_date=20250503T132539
[2025-05-03T13:25:39.346+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-03T13:25:39.348+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-03T13:25:39.349+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-03 13:24:29.634814+00:00
[2025-05-03T13:25:39.349+0000] {logging_mixin.py:190} INFO - Task hostname:8280c28b7f0f operator:PythonOperator
[2025-05-03T13:25:39.372+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-03T13:25:39.441+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T13:25:39.445+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
