[2025-05-06T23:04:08.872+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-06T23:04:08.924+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-06T20:00:25.137792+00:00 [queued]>
[2025-05-06T23:04:08.945+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-06T20:00:25.137792+00:00 [queued]>
[2025-05-06T23:04:08.948+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 5
[2025-05-06T23:04:08.973+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): model_data> on 2025-05-06 20:00:25.137792+00:00
[2025-05-06T23:04:08.992+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=9404) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-06T23:04:08.997+0000] {standard_task_runner.py:72} INFO - Started process 9419 to run task
[2025-05-06T23:04:08.997+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'model_data', 'manual__2025-05-06T20:00:25.137792+00:00', '--job-id', '661', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpc3wmcpy4']
[2025-05-06T23:04:09.001+0000] {standard_task_runner.py:105} INFO - Job 661: Subtask model_data
[2025-05-06T23:04:09.089+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.model_data manual__2025-05-06T20:00:25.137792+00:00 [running]> on host 8280c28b7f0f
[2025-05-06T23:04:09.291+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='model_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T20:00:25.137792+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T20:00:25.137792+00:00'
[2025-05-06T23:04:09.295+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-06T23:04:09.297+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-06T23:04:09.298+0000] {logging_mixin.py:190} INFO - Current task name:model_data state:running start_date:2025-05-06 23:04:08.925840+00:00
[2025-05-06T23:04:09.301+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-06T23:04:09.302+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-06T23:04:09.321+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-06T23:04:09.518+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-06T23:04:09.545+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-06T23:04:09.547+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=model_data, run_id=manual__2025-05-06T20:00:25.137792+00:00, execution_date=20250506T200025, start_date=20250506T230408, end_date=20250506T230409
[2025-05-06T23:04:09.632+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-06T23:04:09.635+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-06T23:04:09.636+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-06 23:00:53.773813+00:00
[2025-05-06T23:04:09.640+0000] {logging_mixin.py:190} INFO - Task hostname:8280c28b7f0f operator:PythonOperator
[2025-05-06T23:04:09.700+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-06T23:04:09.772+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-06T23:04:09.793+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
