[2025-05-08T21:52:19.009+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T21:52:19.058+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-08T21:43:14.329156+00:00 [queued]>
[2025-05-08T21:52:19.084+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-08T21:43:14.329156+00:00 [queued]>
[2025-05-08T21:52:19.086+0000] {taskinstance.py:2867} INFO - Starting attempt 5 of 6
[2025-05-08T21:52:19.118+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): model_data> on 2025-05-08 21:43:14.329156+00:00
[2025-05-08T21:52:19.136+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=407) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-08T21:52:19.143+0000] {standard_task_runner.py:72} INFO - Started process 429 to run task
[2025-05-08T21:52:19.143+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'model_data', 'manual__2025-05-08T21:43:14.329156+00:00', '--job-id', '898', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpo_53p3q2']
[2025-05-08T21:52:19.145+0000] {standard_task_runner.py:105} INFO - Job 898: Subtask model_data
[2025-05-08T21:52:19.260+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.model_data manual__2025-05-08T21:43:14.329156+00:00 [running]> on host f90cb465d7e0
[2025-05-08T21:52:19.466+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='elkhalfimaryame@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='model_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T21:43:14.329156+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T21:43:14.329156+00:00'
[2025-05-08T21:52:19.471+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-08T21:52:19.473+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-08T21:52:19.474+0000] {logging_mixin.py:190} INFO - Current task name:model_data state:running start_date:2025-05-08 21:52:19.059872+00:00
[2025-05-08T21:52:19.475+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-08T21:52:19.477+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-08T21:52:19.498+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-08T21:52:19.633+0000] {warnings.py:112} WARNING - /opt/***/dags/storeData.py:223: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-05-08T21:52:19.827+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-08T21:52:19.849+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-08T21:52:19.850+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=model_data, run_id=manual__2025-05-08T21:43:14.329156+00:00, execution_date=20250508T214314, start_date=20250508T215219, end_date=20250508T215219
[2025-05-08T21:52:19.916+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-08T21:52:19.917+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-08T21:52:19.917+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-08 21:43:14.370818+00:00
[2025-05-08T21:52:19.918+0000] {logging_mixin.py:190} INFO - Task hostname:f90cb465d7e0 operator:PythonOperator
[2025-05-08T21:52:19.966+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-08T21:52:20.026+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-08T21:52:20.047+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
