[2025-04-04T18:55:05.642+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-04T18:55:05.680+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews_pipeline.model_data manual__2025-04-04T18:43:20.593923+00:00 [queued]>
[2025-04-04T18:55:05.697+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews_pipeline.model_data manual__2025-04-04T18:43:20.593923+00:00 [queued]>
[2025-04-04T18:55:05.699+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-04T18:55:05.724+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): model_data> on 2025-04-04 18:43:20.593923+00:00
[2025-04-04T18:55:05.744+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=280) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-04T18:55:05.747+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews_pipeline', 'model_data', 'manual__2025-04-04T18:43:20.593923+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpowxfrkqb']
[2025-04-04T18:55:05.749+0000] {standard_task_runner.py:72} INFO - Started process 296 to run task
[2025-04-04T18:55:05.750+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask model_data
[2025-04-04T18:55:05.839+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews_pipeline.model_data manual__2025-04-04T18:43:20.593923+00:00 [running]> on host c3eecb2684dd
[2025-04-04T18:55:05.989+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews_pipeline' AIRFLOW_CTX_TASK_ID='model_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T18:43:20.593923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T18:43:20.593923+00:00'
[2025-04-04T18:55:05.992+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-04T18:55:05.994+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-04T18:55:05.995+0000] {logging_mixin.py:190} INFO - Current task name:model_data state:running start_date:2025-04-04 18:55:05.681680+00:00
[2025-04-04T18:55:05.995+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews_pipeline and current dag run status:running
[2025-04-04T18:55:05.996+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-04T18:55:06.018+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-04-04T18:55:06.102+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-04T18:55:06.119+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-04T18:55:06.121+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews_pipeline, task_id=model_data, run_id=manual__2025-04-04T18:43:20.593923+00:00, execution_date=20250404T184320, start_date=20250404T185505, end_date=20250404T185506
[2025-04-04T18:55:06.159+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-04T18:55:06.160+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-04T18:55:06.164+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews_pipeline queued_at:2025-04-04 18:43:20.618851+00:00
[2025-04-04T18:55:06.165+0000] {logging_mixin.py:190} INFO - Task hostname:c3eecb2684dd operator:PythonOperator
[2025-04-04T18:55:06.212+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-04T18:55:06.253+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T18:55:06.258+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
